### ISSUE TITLE
[HYAK101/Flexible-Connections] Corrections/Optimizations for connecting to compute node via ssh config

### ISSUE THREAD

**Issue by hansemro** [UWrc/UWrc.github.io#124]
I am glad to see this topic included in the documentation as it greatly improves user experience on HYAK. Here, I'd like to make some corrections for things I had issues with and an optimization that removes the need to update the ssh config whenever a different compute node is used.

## Issue 1: User needs to authorize their ssh key before connecting to a compute node

Documentation is missing a crucial step to generate a personal ssh key and authorize that key on HYAK. Without a key, I encountered a `permission denied`  connection error:

```
$ ssh klone-node
hansem7@g3056: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

## Issue 2: `User` may need to be specified under `klone-node` ssh config

Encountered the following error since my local username differs from my UW NetID:

```
$ ssh klone-node
(hansem7@klone.hyak.uw.edu) Password: 
(hansem7@klone.hyak.uw.edu) Duo two-factor login for hansem7
...
hansemro@g3056: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

To fix this, I had to specify User for the compute node's ssh config.

## Updated ssh config for klone compute nodes

One optimization that removes the need to update the compute node's ssh config is to use the wildcard character ? to match a single character. So we could potentially have something like the following:

```
Host n3???
    HostName %h
    User UWNetID
    ProxyJump klone-login
```

This works without changing the ssh config each time you get a different compute node (provided you know the name of the node).

Similarly for mox compute nodes if `mox-login` is defined:
```
Host n2???
    HostName %h
    User UWNetID
    ProxyJump mox-login
```

If there are concerns about potential namespace conflicts, then we could have the following instead:
```
Host n3???.hyak.local
    HostName %h
    User UWNetID
    ProxyJump klone-login
```

**Comment by hansemro** [comment]
@mwanek Any thoughts?

**Comment by mwanek** [comment]
Looks good - just need to replace the instances of `ssh klone-node` with the `squeue` node hostname retrieval snippet. Feel free to make a PR!

**Comment by swartout** [comment]
@mwanek, made a PR updating Issue 1/2.
