### ISSUE TITLE
AlphaFold data innaccurate

### ISSUE THREAD

**Issue by EvanKomp** [UWrc/UWrc.github.io#143]
recently merged: #130 

The module information in that update is correct however it also references data that does not exist in the public location specified.

**Comment by npho** [comment]
Was the [data set documented](https://hyak.uw.edu/docs/data-commons/requirements)? If not, can you do that to be in alignment with the new cluster policy. Thank you!

**Comment by npho** [comment]
Oh, also, I missed this in the original PR for AlphaFold documentation but it's not showing up on the left hand side menu. Could you add it? You would add a line in the [sidebars.js](https://github.com/UWrc/UWrc.github.io/blob/src/sidebars.js) file. Thank you.
